import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const chakraPetch = localFont({
  src: [
    {
      path: '../public/frontendmentor/assets/fonts/chakra-petch/chakra-petch-semibold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/frontendmentor/assets/fonts/chakra-petch/chakra-petch-bold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-chakra-petch',
})

const jetbrainsMono = localFont({
  src: "../public/frontendmentor/assets/fonts/jetbrains-mono/jetbrains-mono-variable.ttf",
  display: 'swap',
  variable: '--font-jetbrains-mono',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${chakraPetch.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <main className="flex flex-col flex-1 items-center justify-center font-sans">
          <div className="flex flex-1 w-full max-w-3xl flex-col items-center justify-between py-32 px-16 sm:items-start">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
